//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibiaMarketRush.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SearchTextPosition {
            get {
                return ((global::System.Drawing.Point)(this["SearchTextPosition"]));
            }
            set {
                this["SearchTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FirstItemPosition {
            get {
                return ((global::System.Drawing.Point)(this["FirstItemPosition"]));
            }
            set {
                this["FirstItemPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FirstValuePositionTop {
            get {
                return ((global::System.Drawing.Point)(this["FirstValuePositionTop"]));
            }
            set {
                this["FirstValuePositionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FirstValuePositionBottom {
            get {
                return ((global::System.Drawing.Point)(this["FirstValuePositionBottom"]));
            }
            set {
                this["FirstValuePositionBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AcceptButtonPosition {
            get {
                return ((global::System.Drawing.Point)(this["AcceptButtonPosition"]));
            }
            set {
                this["AcceptButtonPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSearchTextPositionConfigured {
            get {
                return ((bool)(this["IsSearchTextPositionConfigured"]));
            }
            set {
                this["IsSearchTextPositionConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFirstItemPositionConfigured {
            get {
                return ((bool)(this["IsFirstItemPositionConfigured"]));
            }
            set {
                this["IsFirstItemPositionConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFirstValuePositionConfigured {
            get {
                return ((bool)(this["IsFirstValuePositionConfigured"]));
            }
            set {
                this["IsFirstValuePositionConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAcceptButtonPositionConfigured {
            get {
                return ((bool)(this["IsAcceptButtonPositionConfigured"]));
            }
            set {
                this["IsAcceptButtonPositionConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public decimal NumericUpDownMaxSpent_Value {
            get {
                return ((decimal)(this["NumericUpDownMaxSpent_Value"]));
            }
            set {
                this["NumericUpDownMaxSpent_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal NumericUpDownProfitByValue_Value {
            get {
                return ((decimal)(this["NumericUpDownProfitByValue_Value"]));
            }
            set {
                this["NumericUpDownProfitByValue_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal NumericUpDownProfitByPercentage_Value {
            get {
                return ((decimal)(this["NumericUpDownProfitByPercentage_Value"]));
            }
            set {
                this["NumericUpDownProfitByPercentage_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RadioButtonProfitByValue_Checked {
            get {
                return ((bool)(this["RadioButtonProfitByValue_Checked"]));
            }
            set {
                this["RadioButtonProfitByValue_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RadioButtonProfitByPercentage_Checked {
            get {
                return ((bool)(this["RadioButtonProfitByPercentage_Checked"]));
            }
            set {
                this["RadioButtonProfitByPercentage_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FirstCountPositionTop {
            get {
                return ((global::System.Drawing.Point)(this["FirstCountPositionTop"]));
            }
            set {
                this["FirstCountPositionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FirstCountPositionBottom {
            get {
                return ((global::System.Drawing.Point)(this["FirstCountPositionBottom"]));
            }
            set {
                this["FirstCountPositionBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFirstCountPositionConfigured {
            get {
                return ((bool)(this["IsFirstCountPositionConfigured"]));
            }
            set {
                this["IsFirstCountPositionConfigured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ChangeCountPosition {
            get {
                return ((global::System.Drawing.Point)(this["ChangeCountPosition"]));
            }
            set {
                this["ChangeCountPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsChangeCountPositionConfigured {
            get {
                return ((bool)(this["IsChangeCountPositionConfigured"]));
            }
            set {
                this["IsChangeCountPositionConfigured"] = value;
            }
        }
    }
}
